import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { TextProvider } from "@/app/context/TextContext"; // TextProvider のインポート

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <TextProvider>
          {children}
        </TextProvider>
      </body>
    </html>
  );
}
